name: CI Build & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Simulating Tests
        run: |
          echo "Simulando build e testes..."
          ls -R
          echo "Testes finalizados com sucesso!"