name: Production Promote Staging on PR Merge
on:
  pull_request:
    types: [closed]
    branches: [ main ]
jobs:
  promote-to-production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Promote Staging to Production
        run: |
          echo "Copiando staging/index.html para index.html"
          cp staging/index.html index.html

      - name: Commit and Push to gh-pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          if git diff-index --quiet HEAD; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "feat(prod): Promove staging para produção via Action"
            echo "Commit enviado ao gh-pages"
            git push
          fi